image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: ygZ/Wjv5cu9itNSNUN6z9sguTvsgyQ2txQcXmluFAeuSnABXX6E3gd1fGnimVVAonu6apFd/xobbHM56rQ0p15NQU0ZpGgk06LC1Yl90ArAgaMvIlr0Zrtlvvdrr4xUW

install:
- pip install -r requirements.txt

build_script:
- flet build  --product 'Names.rand' --build-version "0.2.0" --copyright "Copyright (c) 2024 Son Link." $target

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019
  
  init:
    - ps: $target=windows

  after_build:
  - 7z a Names.rand-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: Names.rand-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  init:
    - $target=macos

  after_build:
  - tar -czvf Names.rand-macos.tar.gz -C dist Names.rand.app

  artifacts:
  - path: Names.rand-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu
  
  init:
    - $target=linux

  after_build:
  - tar -czvf Names.rand-linux.tar.gz -C dist Names.rand

  artifacts:
  - path: Names.rand-linux.tar.gz

